# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{retrying_proxy}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher J. Bottaro"]
  s.date = %q{2011-01-07}
  s.description = %q{A simple gem to help you retry methods and deal with transient failures.}
  s.email = %q{cjbottaro@alumni.cs.utexas.edu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/retrying_proxy.rb",
     "lib/retrying_proxy/active_support.rb",
     "lib/retrying_proxy/base.rb",
     "lib/retrying_proxy/proxy.rb",
     "retrying_proxy.gemspec",
     "test/helper.rb",
     "test/test_base.rb",
     "test/test_coverage.rb",
     "test/test_proxy.rb",
     "test/test_retrying_proxy.rb"
  ]
  s.homepage = %q{http://github.com/cjbottaro/retrying_proxy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple gem to help you retry methods and deal with transient failures.}
  s.test_files = [
    "test/helper.rb",
     "test/test_base.rb",
     "test/test_coverage.rb",
     "test/test_proxy.rb",
     "test/test_retrying_proxy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

